stages:
  - test
  - build
  - deploy

test:
  image: rust
  stage: test
  script:
    - cargo test

check:format:
  image: rust
  stage: test
  script:
    - cargo fmt -- --check

check:features:
  image: rust
  stage: test
  script:
    - cargo build --no-default-features
    - cargo build --no-default-features --features storage-lru
    - cargo build --no-default-features --features storage-sqlx
    - cargo build --no-default-features --features storage-sled
    - cargo build --no-default-features --features serve-http

build:amd64:
  image: rust
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/cloudfs
    expire_in: 1 week

doc:
  image: rust
  stage: build
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week

pages:
  dependencies:
    - build:amd64
    - doc
  stage: deploy
  script:
    - mkdir -p public/nightly
    - mv target/doc public/doc
    - mv target/release/cloudfs public/nightly/cloudfs-amd64
  artifacts:
    paths:
      - public
    expire_in: 1 week
