stages:
  - setup
  - test
  - build
  - deploy

docker:
  image: docker
  stage: setup
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -t "$CI_REGISTRY_IMAGE/rust"
    - docker push "$CI_REGISTRY_IMAGE/rust"
  only:
    refs:
      - master
    changes:
      - Dockerfile

test:
  image: "$CI_REGISTRY_IMAGE/rust"
  stage: test
  script:
    - cargo test

check:format:
  image: "$CI_REGISTRY_IMAGE/rust"
  stage: test
  script:
    - cargo fmt -- --check

check:features:
  image: "$CI_REGISTRY_IMAGE/rust"
  stage: test
  script:
    - cargo build --no-default-features
    - cargo build --no-default-features --features storage-lru
    - cargo build --no-default-features --features storage-sqlx
    - cargo build --no-default-features --features storage-sled
    - cargo build --no-default-features --features serve-http

build:amd64:
  image: "$CI_REGISTRY_IMAGE/rust"
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/cloudfs
    expire_in: 1 week

doc:
  image: "$CI_REGISTRY_IMAGE/rust"
  stage: build
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week

pages:
  dependencies:
    - build:amd64
    - doc
  stage: deploy
  script:
    - mkdir -p public/nightly
    - mv target/doc public/doc
    - mv target/release/cloudfs public/nightly/cloudfs-amd64
  artifacts:
    paths:
      - public
    expire_in: 1 week
