[package]
name = "cloudfs"
version = "0.1.0"
edition = "2021"
authors = ["Patrick Elsen <pelsen@xfbs.net>"]
description = "Distributed file system"
license = "MIT"
repository = "https://github.com/xfbs/cloudfs"

[dependencies]
